{
 "title": "PJX Overview",
 "time": { "from": "2026-08-09T02:11:49.094Z", "to": "2026-08-09T02:12:55.049Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "2b63d5fd", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "pjx-graphql-apollo",
        "pjx-api-node"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "p95 latency by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (job, le) (rate(http_server_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Error rate by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job)(rate(http_server_request_duration_seconds_count{http_response_status_code=~\"5..\"}[5m])) or vector(0)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request rate by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (job) (rate(http_server_request_duration_seconds_count[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}