# ./docker-compose.yml

version: '3.8'

services:
  pjx-graphql-apollo:
    build:
      context: ./projects/pjx-graphql-apollo
    container_name: pjx-graphql-apollo-dev
    command: npm run dev
    volumes:
      - .:/usr/graphql
    ports:
      - 4000:4000
    networks:
      - pjx-network

  pjx-api-dotnet:
    build:
      context: ./projects/pjx-api-dotnet/src/Pjx_Api/
      dockerfile: Dockerfile
    container_name: pjx-api-dotnet-dev
    volumes:
      - .:/usr/api-dotnet
    ports:
      - 6001:80
    networks:
      - pjx-network
    environment:
      - PJX_SSO__AUTHORITY=https://pjx-sso-identityserver

  pjx-api-node:
    build:
      context: ./projects/pjx-api-node
    container_name: pjx-api-node-dev
    command: npm start
    volumes:
      - .:/usr/api-node
    ports:
      - 8081:8081
    networks:
      - pjx-network

  pjx-web-react:
    build:
      context: ./projects/pjx-web-react
    container_name: pjx-web-react-dev
    command: npm start
    volumes:
      - .:/usr/react
    ports:
      - 3000:3000
    networks:
      - pjx-network
    stdin_open: true 
    tty: true

  pjx-sso-identityserver:
    build:
      context: ./projects/pjx-sso-identityserver
    container_name: pjx-sso-identityserver-dev
    ports:
      - 5001:80
      - 5002:443
      - 443:443
    networks:
      - pjx-network
    environment:
      - PJX_SSO__CERTIFICATE=pjx-sso-identityserver.rsa_2048.cert.pfx
      - PJX_SSO__PASSWORD=password
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/pjx-sso-identityserver.rsa_2048.cert.pfx


networks:
  pjx-network:
    name: pjx-network
    driver: bridge
