apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-apollo-deployment
  labels:
    app: pjx-apollo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pjx-apollo
  template:
    metadata:
      labels:
        app: pjx-apollo
    spec:
      containers:
      - name: pjx-apollo
        image: mikelauawaremd/pjx-graphql-apollo:v0.0.3
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-apollo-service
spec:
  type: NodePort
  selector:
    app: pjx-apollo
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30400