apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-node-deployment
  labels:
    app: {{ .Values.node_api.appName }}
spec:
  replicas: {{ .Values.node_api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.node_api.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.node_api.appName }}
    spec:
      containers:
      - name: {{ .Values.node_api.appName }}
        image: mikelauawaremd/pjx-api-node:v0.0.2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-node-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.node_api.appName }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30881