apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-dotnet-deployment
  labels:
    app: {{ .Values.dotnetApi.appName}}
spec:
  replicas: {{ .Values.dotnetApi.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.dotnetApi.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.dotnetApi.appName}}
    spec:
      containers:
      - name: {{ .Values.dotnetApi.appName}}
        image: {{ include "pjx.image" (dict "root" $ "svc" .Values.dotnetApi) }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: PJX_SSO__AUTHORITY
          valueFrom:
            configMapKeyRef:
              name: pjx-config
              key: sso-authority
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-dotnet-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.dotnetApi.appName}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http  #adding name: http to each port lets the Ingress reference the port by name instead of number