apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-dotnet-deployment
  labels:
    app: {{ .Values.dotnet_api.appName}}
spec:
  replicas: {{ .Values.dotnet_api.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.dotnet_api.appName}}
  template:
    metadata:
      labels:
        app: {{ .Values.dotnet_api.appName}}
    spec:
      containers:
      - name: {{ .Values.dotnet_api.appName}}
        image: mikelauawaremd/pjx-api-dotnet:v0.0.1
        ports:
        - containerPort: 80
        env:
        - name: PJX_SSO__AUTHORITY
          valueFrom:
            configMapKeyRef:
              name: pjx-config
              key: sso-authority
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-dotnet-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.dotnet_api.appName}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30601