apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-node-deployment
  labels:
    app: {{ .Values.nodeApi.appName }}
spec:
  replicas: {{ .Values.nodeApi.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.nodeApi.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.nodeApi.appName }}
    spec:
      containers:
      - name: {{ .Values.nodeApi.appName }}
        image: {{ include "pjx.image" (dict "root" $ "svc" .Values.nodeApi) }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-node-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.nodeApi.appName }}
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http