apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-react-deployment
  labels:
    app: {{ .Values.react.appName }}
spec:
  replicas: {{ .Values.react.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.react.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.react.appName }}
    spec:
      containers:
      - name: {{ .Values.react.appName }}
        image: mikelauawaremd/pjx-web-react:v0.0.6
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: pjx-react-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.react.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100