apiVersion: v1
kind: ConfigMap
metadata:
  name: pjx-config
data:
  sso-authority: {{ .Values.ssoUrl }}
  dotnet-connection: {{ .Values.connectionStrings.dotnetApi | quote }}
  sso-connection:    {{ .Values.connectionStrings.sso | quote }}
