apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-node-deployment
  labels:
    app: pjx-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pjx-node
  template:
    metadata:
      labels:
        app: pjx-node
    spec:
      containers:
      - name: pjx-node
        image: mikelauawaremd/pjx-api-node:v0.0.2
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-node-service
spec:
  type: NodePort
  selector:
    app: pjx-node
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30881