apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-sso-deployment
  labels:
    app: pjx-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pjx-sso
  template:
    metadata:
      labels:
        app: pjx-sso
    spec:
      containers:
      - name: pjx-sso
        image: mikelauawaremd/pjx-sso-identityserver:v0.0.1
        ports:
        - containerPort: 5002
        env:
        - name: PJX_SSO__PASSWORD
          valueFrom:
            secretKeyRef:
              name: pjx-secret
              key: sso-password
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: pjx-secret
              key: certificate-password
        - name: PJX_SSO__CERTIFICATE
          value: pjx-sso-identityserver.rsa_2048.cert.pfx
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: https://+:443;http://+:80
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: /app/pjx-sso-identityserver.rsa_2048.cert.pfx
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-sso-service
spec:
  type: NodePort
  selector:
    app: pjx-sso
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30501