apiVersion: apps/v1
kind: Deployment
metadata:
  name: pjx-dotnet-deployment
  labels:
    app: pjx-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pjx-dotnet
  template:
    metadata:
      labels:
        app: pjx-dotnet
    spec:
      containers:
      - name: pjx-dotnet
        image: mikelauawaremd/pjx-api-dotnet:v0.0.1
        ports:
        - containerPort: 80
        env:
        - name: PJX_SSO__AUTHORITY
          valueFrom:
            configMapKeyRef:
              name: pjx-config
              key: sso-authority
---
apiVersion: v1
kind: Service
metadata:
  name: pjx-dotnet-service
spec:
  type: NodePort
  selector:
    app: pjx-dotnet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30601